[tool.poetry]
name = "aoc2022"
version = "0.1.0"
description = ""
authors = ["Jian Yuan Lee <jianyuan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
